services:
  emulator:
    image: budtmo/docker-android
    container_name: emulator
    privileged: true
    ports:
      - "6080:6080"  # Port for VNC access
      - "5554:5554"  # Emulator control port
      - "5555:5555"  # ADB communication port
    networks:
      - android-net
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    devices:
      - /dev/kvm
      
  flutter:
    image: ghcr.io/cirruslabs/flutter
    container_name: flutter
    volumes:
      - ./:/mobile
    working_dir: /mobile
    networks:
      - android-net
    command: >
      bash -c "./prepare_submodules.sh &&
               flutter pub get &&
               flutter build apk --debug &&
               adb connect emulator:5555 &&
               adb install -r build/app/outputs/flutter-apk/app-debug.apk"

networks:
  android-net:
    driver: bridge