name: Build APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/cirruslabs/flutter:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true  # Checkout submodules

    - name: Configure Git safe directory
      run: git config --global --add safe.directory /__w/mobile/mobile

    - name: Initialize and update submodules
      run: |
        git submodule sync
        git submodule update --init --force --depth=1 --remote

    - name: Set up environment variables
      run: |
        echo "deezerClientId=1" >> $GITHUB_ENV
        echo "deezerClientSecret=2" >> $GITHUB_ENV
        echo "lastFmApiKey=3" >> $GITHUB_ENV
        echo "lastFmApiSecret=4" >> $GITHUB_ENV

    - name: Process submodules
      run: |
        mainProjectDir=$(pwd)

        invoke_build_runner() {
            dir=$1
            name=$2
            echo "Processing $name at $dir"
            cd $dir

            echo "Running 'flutter pub get' for $name"
            flutter pub get

            echo "Running 'dart run build_runner build --delete-conflicting-outputs' for $name from main project"
            dart run build_runner build --delete-conflicting-outputs

            echo "Running 'flutter clean' for $name"
            cd $dir
            flutter clean
        }

        submodule_paths=$(git submodule status | awk '{ print $2 }')
        for submodule in $submodule_paths; do
            submodulePath="$mainProjectDir/$submodule"
            invoke_build_runner $submodulePath "submodule $submodule"
        done

        invoke_build_runner $mainProjectDir "main project"

        cd $mainProjectDir
        echo "Running 'flutter clean' for the main project"
        flutter clean
        echo "Running 'flutter pub get' for the main project"
        flutter pub get

    - name: Set up keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
